spring:
  data:
    mongodb:
      #uri: mongodb://localhost:27017/care
      uri: mongodb+srv://edumongo:rrTwCtNqLp77pV5j@cluster0.t9vac.mongodb.net/care
      auto-index-creation: true
      socketTimeout: 120000    #  tiempo máximo que una operación puede tardar en la base de datos, en milisegundos.
      connectTimeout: 120000   # tiempo maximo para establecer una conexion con la bbdd, en milisegundos.
      maxWaitTime: 200000     # tiempo maximo que la app espera para obtener un hilo de la bbdd, en milisegundos.

server:
  #port: 9096
  error:
    include-message: always

logging:
  level:
    org:
      #mongodb.driver: DEBUG
      springframework.data.mongodb: DEBUG

# Parametrizaciones
#

protocol: http
socket: localhost:8080
